### ISSUE TITLE
css clamp() syntax error

### ISSUE THREAD

**Issue by LukaszJaro** [shellscape/postcss-values-parser#136]
- Windows 10
- Node Version: v14.15.0
- postcss-values-parser 2.0.1
- gulp-postcss 8.0.0

### How Do We Reproduce?

Hi,

I'm using custom css properties, they are imported into the relevant stylesheets with @import '_custom-properties.css';

However when using clamp() with math it causes error. In addition the math only breaks using @import in stylesheet.

CSS to reproduce

custom-properties.css - add properties below
--font-size-larger: clamp(1.25rem, 0.9423rem + 1.5385vw, 1.75rem);
--font-size-huge: clamp(1.5rem, 1.0294rem + 2.3529vw, 2.5rem);

content.css - add line below to very top of stylesheet
@import "_custom-properties.css";

### Expected Behavior
CSS properties to build properly with no error

### Actual Behavior
Error

[08:51:01] 'styles' errored after 16 s
[08:51:01] ParserError in plugin "gulp-postcss"
Message:
    Syntax Error at line: 1, column 26
Details:
    fileName: C:\project\assets\css\src\content.css

Stack:
ParserError: Syntax Error at line: 1, column 26
    at Parser.error (C:\project\node_modules\postcss-values-parser\lib\parser.js:127:11)
    at Parser.operator (C:\project\node_modules\postcss-values-parser\lib\parser.js:183:18)
    at Parser.parseTokens (C:\project\node_modules\postcss-values-parser\lib\parser.js:245:14)
    at Parser.loop (C:\project\node_modules\postcss-values-parser\lib\parser.js:132:12)
    at Parser.parse (C:\project\node_modules\postcss-values-parser\lib\parser.js:51:17)
    at parse (C:\project\node_modules\postcss-custom-properties\src\lib\postcss-values-parser.js:4:29)
    at parse (C:\project\node_modules\postcss-custom-properties\src\lib\get-custom-properties-from-root.js:25:37)
    at Array.forEach (<anonymous>)
    at forEach (C:\project\node_modules\postcss-custom-properties\src\lib\get-custom-properties-from-root.js:20:23)
    at Array.forEach (<anonymous>)

**Comment by shellscape** [comment]
Thanks for the issue. PRs are welcome

**Comment by LukaszJaro** [comment]
@peteramelang, that does in fact work! thank you for sharing this, this is so useful for responsive typography :)

**Comment by shellscape** [comment]
This is resolved in the `major/css-tree` branch, which will be released as v7
