### ISSUE TITLE
Cannot parse `url()` with unquoted data url

### ISSUE THREAD

**Issue by OpportunityLiu** [shellscape/postcss-values-parser#140]
- Operating System (or Browser): Windows 10
- Node Version: v16.13.0
- postcss-values-parser Version: 6.0.1

### How Do We Reproduce?

```js
require('postcss-values-parser').parse(
 `url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAL0lEQVQoz2NgCD3x//9/BhBYBWdhgFVAiVW4JBFKGIa4AqD0//9D3pt4I4tAdAMAHTQ/j5Zom30AAAAASUVORK5CYII=)`,
)
```

### Actual Behavior

```
C:\Users\lzy\Documents\Sources\node_modules\postcss\lib\parser.js:518
    throw this.input.error('Unknown word', tokens[0][2])
    ^

CssSyntaxError: <css input>:1:15: Unknown word
    at Input.error (C:\Users\lzy\Documents\Sources\node_modules\postcss\lib\input.js:123:16)
    at ValuesParser.unknownWord (C:\Users\lzy\Documents\Sources\node_modules\postcss\lib\parser.js:518:22)
    at ValuesParser.unknownWord (C:\Users\lzy\Documents\Sources\node_modules\postcss-values-parser\lib\ValuesParser.js:199:13)
    at ValuesParser.other (C:\Users\lzy\Documents\Sources\node_modules\postcss-values-parser\lib\ValuesParser.js:110:10)
    at ValuesParser.parse (C:\Users\lzy\Documents\Sources\node_modules\postcss-values-parser\lib\ValuesParser.js:135:16)
    at parse (C:\Users\lzy\Documents\Sources\node_modules\postcss-values-parser\lib\index.js:21:12)
    at Function.fromTokens (C:\Users\lzy\Documents\Sources\node_modules\postcss-values-parser\lib\nodes\Func.js:177:20)
    at ValuesParser.unknownWord (C:\Users\lzy\Documents\Sources\node_modules\postcss-values-parser\lib\ValuesParser.js:152:12)
    at ValuesParser.other (C:\Users\lzy\Documents\Sources\node_modules\postcss-values-parser\lib\ValuesParser.js:110:10)
    at ValuesParser.parse (C:\Users\lzy\Documents\Sources\node_modules\postcss-values-parser\lib\ValuesParser.js:135:16) {
  reason: 'Unknown word',
  source: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAL0lEQVQoz2NgCD3x//9/BhBYBWdhgFVAiVW4JBFKGIa4AqD0//9D3pt4I4tAdAMAHTQ/j5Zom30AAAAASUVORK5CYII=',
  line: 1,
  column: 15,
  input: {
    line: 1,
    column: 15,
    source: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAL0lEQVQoz2NgCD3x//9/BhBYBWdhgFVAiVW4JBFKGIa4AqD0//9D3pt4I4tAdAMAHTQ/j5Zom30AAAAASUVORK5CYII='
  }
}
```

**Comment by shellscape** [comment]
This is resolved in the `major/css-tree` branch, which will be released as v7

**Comment by JackHowa** [comment]
running into this problem too; any news on shipping this branch update?
