### ISSUE TITLE
The color-mod function should not require loose mode

### ISSUE THREAD

**Issue by jonathantneal** [shellscape/postcss-values-parser#40]
* Node Version: 9.3.0
* NPM Version: 5.6.0
* postcss-values-parser Version: 1.3.1

This issue is regarding a problem with:
- [X] Standard CSS

### Description

Parsing color-mod should probably work outside loose mode.

See https://drafts.csswg.org/css-color/#modifying-colors

```css
test {
  color-mod(blue blackness(+ 20%));
}
```

Note that the space after the plus is required to distinguish between setting the blackness of blue to 20% versus adding 20% blackness to the existing blackness of blue.

### Error

```
ParserError: Syntax Error at line: 1, column 26
    at Parser.error (/node_modules/postcss-values-parser/lib/parser.js:116:11)
    at Parser.operator (/node_modules/postcss-values-parser/lib/parser.js:172:18)
    at Parser.parseTokens (/node_modules/postcss-values-parser/lib/parser.js:234:14)
    at Parser.loop (/node_modules/postcss-values-parser/lib/parser.js:121:12)
    at Parser.parse (/node_modules/postcss-values-parser/lib/parser.js:50:17)
    at Object.<anonymous> (/test.js:4:44)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

### Expected Behavior

It should parse without error.

### Actual Behavior

It throws an error.

### How can we reproduce the behavior?

```js
require('postcss-values-parser')('color-mod(blue blackness(+ 20%))').parse();
```

**Comment by shellscape** [comment]
CSS blows my mind - such an incredible amount I don't know. Agreed it shouldn't require loose mode. Would happily review a PR for this modification.

**Comment by shellscape** [comment]
Happy to report that the offending css value passes in the `next` branch, and doesn't require loose mode. I'll be releasing a beta of 3.0.0 later today. Thanks for reporting the issue. Cheers 🍻
